import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "Next.js App",
    default: "Next.js Tutorial",
    template: "%s | Next.js App", // %s will be replaced by the title in children
  },  
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ backgroundColour: "blue", padding: "1rem" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColour: "ghostwhite", padding: "1rem" }}>
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
